- name: Delete the entire infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars:
        dir: ../vars

    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: "{{region}}"
        instance_ids: '{{ ec2_instance_id }}'
        wait: yes
        wait-timeout: 200
        
    
    - name: Delete the internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcId}}"
        region: "{{region}}"
        state: absent

    - name: Delete all subnets
      ec2_vpc_subnet:
        vpc_id: "{{vpcId}}"
        region: "{{region}}"
        state: absent
        cidr: "{{item}}"
      loop: 
        - "{{PubSub1Cidr}}"
        - "{{PubSub2Cidr}}"
        - "{{PubSub3Cidr}}"
        - "{{PrivSub1Cidr}}"
        - "{{PrivSub2Cidr}}"
        - "{{PrivSub3Cidr}}"

    - name: Delete all routes tables
      ec2_vpc_route_table:
        vpc_id: "{{vpcId}}"
        region: "{{region}}"
        lookup: id
        state: absent
        route_table_id: "{{item}}"
      loop:
        - "{{public_route_tb}}"
        - "{{private_route_tb}}"
    
    - name: Delete the vpc
      ec2_vpc_net:
        name: java-app-vpc
        region: "{{region}}"
        cidr_block: "{{vpcCidr}}"
        purge_cidrs: true
        state: absent 