- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: ../vars/vpc_setup.yml
    
    - name: Create VPC for java application
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        region: "{{region}}"
        state: "{{state}}"
      register: vpcOutput
    
    - name: Print the output
      debug:
        var: vpcOutput
    
    - name: Create the 1st public subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcOutput.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: java-app-public-subnet-1
      register: public_subnet_1_output

    - name: Create the 2st public subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcOutput.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: java-app-public-subnet-2
      register: public_subnet_2_output
    
    - name: Create the 3rd public subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcOutput.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: java-app-public-subnet-3
      register: public_subnet_3_output

    - name: Create the 1st private subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcOutput.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PrivSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: java-app-private-subnet-1
      register: private_subnet_1_output

    - name: Create the 2nd private subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcOutput.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PrivSub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: java-app-private-subnet-2
      register: private_subnet_2_output

    - name: Create the 3rd private subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcOutput.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PrivSub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: java-app-private-subnet-3
      register: private_subnet_3_output  